src/Entity/Cookie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CookieRepository")
 */
class Cookie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\Column(type="text")
     */
    private $politica_cookies;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getPoliticaCookies(): ?string
    {
        return $this->politica_cookies;
    }

    public function setPoliticaCookies(string $politica_cookies): self
    {
        $this->politica_cookies = $politica_cookies;

        return $this;
    }
}

src/Entity/Legal.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LegalRepository")
 */
class Legal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\Column(type="text")
     */
    private $aviso_legal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getAvisoLegal(): ?string
    {
        return $this->aviso_legal;
    }

    public function setAvisoLegal(string $aviso_legal): self
    {
        $this->aviso_legal = $aviso_legal;

        return $this;
    }
}

templates/partials/footer.html.twig
<footer class="footer">
    <div class="container footer-inner">
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <div class="footer-item clearfix">
                    <img src="{{ asset('assets/images/logoCompleto.png') }}" alt="logo" class="f-logo">
                    <ul class="contact-info">
                        <li>
                            <i class="flaticon-pin"></i>{{ datos.direccion }}
                        </li>
                        <li>
                            <i class="flaticon-mail"></i><a href="mailto:{{ datos.email }}">{{ datos.email }}</a>
                        </li>
                        <li style="padding-left: 0">
                            <span>Tel. ventas: </span><a href="tel:{{ datos.movil }}">{{ datos.movil }}</a>
                        </li>
                        <li style="padding-left: 0">
                            <span>Tel. Consultas u Oficina: </span>{{ datos.telefono }}
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                    <div class="social-list-2">
                        <ul>
                            {% if datos.facebook %}
                                <li><a href="{{ datos.facebook  }}" class="facebook-bg" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            {% endif %}
                            {% if datos.twitter %}
                                <li><a href="{{ datos.twitter }}" class="twitter-bg" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            {% endif %}
                            {% if datos.instagram %}
                                <li><a href="{{ datos.instagram }}" class="google-bg" target="_blank"><i class="fa fa-instagram"></i></a></li>
                            {% endif %}
                            {% if datos.linkedin %}
                                <li><a href="{{ datos.linkedin }}" class="linkedin-bg" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6">
                <div class="footer-item">
                    <h4>
                        Accesos
                    </h4>
                    <ul class="links">
                        <li>
                            <a href="{{ path('home') }}">Home</a>
                        </li>
                        <li>
                            <a href="{{ path('automoviles') }}">Automóviles</a>
                        </li>
                        <li>
                            <a href="{{ path('servicios') }}">Servicios</a>
                        </li>
                        <li>
                            <a href="{{ path('contacto') }}">Contacto</a>
                        </li>
                        <li>
                            <a href="{{ path('novedades') }}">Noticias</a>
                        </li>
                        <li>
                            <a href="{{ path('cookies') }}">Política de Cookies</a>
                        </li>
                        <li>
                            <a href="{{ path('privacidad') }}">Política de Privacidad</a>
                        </li>
                        <li>
                            <a href="{{ path('legal') }}">Aviso Legal</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                <div class="recent-posts footer-item">
                    <h4>Últimos modelos</h4>
                    {{ render(controller('App\\Controller\\LayoutController:getUltimosModelos')) }}
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <div class="footer-item clearfix">
                    <h4>Subscríbete</h4>
                    <div class="Subscribe-box">
                        <p>Entérate de las últimas ofertas y novedades en automóviles.</p>
                         <div id="alert" class="mb-2"></div>
                        {{ form_start(newsletter, {'attr': {'class': 'form-inline', 'id': 'newsletterForm'}}) }}
                        {{ form_errors(newsletter) }}
                        {{ form_widget(newsletter.email) }}
                        <button type="submit" class="btn"><i class="fa fa-paper-plane"></i></button>
                        <p class="mb-0 mt-2">{{ form_widget(newsletter.legal) }}
                        <label for="newsletter_legal">Acepto las <strong><a href="{{ path("legal") }}">condiciones legales.</a></strong></label></p>
                        <p class="mb-0">{{ form_widget(newsletter.consentimiento) }}
                        <label for="newsletter_consentimiento">Consiento recibir emails comerciales con Ofertas y Novedades. Más infomación en <strong><a href="{{ path('privacidad') }}">Política de Privacidad</a></strong></label>
                        {{ form_end(newsletter) }}</p>
                    </div>
                </div>
            </div>
            <div class="col-xl-12 col-lg-12">
                <p class="copy sub-footer">© 2019 AUTOMÓVILES LUCENTUM</p>
            </div>
        </div>
    </div>
</footer>
<style type="text/css">
input[type=checkbox]:checked + label:before{
    display: none!important;
}
.Subscribe-box p { line-height: 20px;  }
.Subscribe-box label {display:inline; font-size:11px}
</style>
<script src="{{ asset('assets/js/jquery-2.2.0.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('assets/js/jquery.serializeObject.min.js') }}"></script>
<script>
    //$(document).on("click", ".Subscribe-box .btn", function(e){
    $("#newsletterForm").on('submit',(function(e) {
      e.preventDefault();
      // get the serialized properties and values of the form 
      var form_data =  $( this ).serialize();

      // the actual request to your newAction
      $.ajax({
        url: '{{ path('newsletter') }}',
        type: 'POST',
        dataType: 'json',
        data: form_data,
        success:function(response){
            $("#alert").empty();
            if (response.status == 'success') {
                htmlPartial = '<div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+response.message+'</div>';
            } else {
                htmlPartial = '<div class="alert alert-danger mb-0" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+response.message+'</div>';
            }
            $("#alert").html(htmlPartial);
            document.getElementById("newsletterForm").reset();
        }
      });
    }));
</script>

templates/partials/politicas.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<!-- Sub banner start -->
<div class="sub-banner" style="background: rgba(0, 0, 0, 0.04) url({% path contacto.banner, 'reference' %});background-size: cover;background-position: center center;background-repeat: no-repeat;position: relative;">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Servicios</h1>
            <ul class="breadcrumbs">
                <li><a href="{{ path('home') }}">Home</a></li>
                {% if flag == 'politica_cookies' %}
                    <li class="active">Política de Cookies</li>
                {% elseif flag == 'aviso_legal' %}
                    <li class="active">Aviso Legal</li>
                {% else %}
                    <li class="active">Política de Privacidad</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->
<!-- Politicas start -->
<div class="services content-area">
    <div class="container">
        <!-- Main title -->
        <div class="main-title text-center">
            <h1>{{ content.titulo }}</h1>
        </div>
        <div class="row">
                <div class="col">
                    <div class="service-info">
                        <div class="detail">
                            {% if flag == 'politica_cookies' %}
                                <p>{{ content.politicaCookies|raw }}</p>
                            {% elseif flag == 'aviso_legal' %}
                                <p>{{ content.avisoLegal|raw }}</p>
                            {% else %}
                                <p>{{ content.politicaPrivacidad|raw }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>
<!-- Politicas end -->
{% endblock %}