src/Entity/Automovil.php
<?php

namespace App\Entity;

use App\Application\Sonata\MediaBundle\Entity\Gallery;
use App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia;
use App\Application\Sonata\MediaBundle\Entity\Media;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AutomovilRepository")
 */
class Automovil
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Marca", inversedBy="automoviles")
     */
    private $marca;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modelo;

    /**
     * @ORM\Column(type="integer")
     */
    private $precio;

    /**
     * @ORM\Column(type="integer")
     */
    private $anio;

    /**
     * @ORM\Column(type="integer")
     */
    private $kilometraje;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $color;

    /**
     * @ORM\Column(type="integer")
     */
    private $plazas;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $puertas;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cambio", inversedBy="automovils")
     */
    private $cambio;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Combustible", inversedBy="automoviles")
     */
    private $combustible;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descripcion;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_alta;

    /**
     * @Gedmo\Timestampable(on="change", field="estado.id", value="2")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_reserva;

    /**
     * @Gedmo\Timestampable(on="change", field="estado.id", value="1")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_venta;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_modificacion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Condicion", inversedBy="automoviles")
     */
    private $condicion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Estado", inversedBy="automoviles")
     */
    private $estado;

    /**
     * @ORM\OneToOne(targetEntity="App\Application\Sonata\MediaBundle\Entity\Media", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $imagen_destacada;

    /**
     * @ORM\OneToOne(targetEntity="App\Application\Sonata\MediaBundle\Entity\Media", cascade={"persist", "remove"})
     */
    private $video;

//    /**
//     * @ORM\ManyToOne(targetEntity="App\Application\Sonata\MediaBundle\Entity\Media", inversedBy="automovil" ,cascade={"persist", "remove"})
//     */
//    private $galeria;

    /**
     * @var array
     * @ORM\Column(type="array", nullable=true)
     */
    protected $files = [];

    /**
     * {@inheritdoc}
     */
    public function setFiles(array $files = [])
    {
        $this->files = $files;
    }

    /**
     * {@inheritdoc}
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Automovil", inversedBy="relacionados")
     */
    private $automovil;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Automovil", mappedBy="automovil")
     */
    private $relacionados;

    /**
     * @ORM\Column(type="boolean")
     */
    private $destacado;

    /**
     * @ORM\Column(type="boolean")
     */
    private $oferta;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $potencia;

 

    public function __toString() {
        return $this->getMarca().' '.$this->getModelo();
    }

    public function __construct()
    {
        $this->relacionados = new ArrayCollection();
        $this->automovil = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarca(): ?Marca
    {
        return $this->marca;
    }

    public function setMarca(?Marca $marca): self
    {
        $this->marca = $marca;

        return $this;
    }

    public function getModelo(): ?string
    {
        return $this->modelo;
    }

    public function setModelo(string $modelo): self
    {
        $this->modelo = $modelo;

        return $this;
    }

    public function getPrecio(): ?int
    {
        return $this->precio;
    }

    public function setPrecio(int $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getAnio(): ?int
    {
        return $this->anio;
    }

    public function setAnio(int $anio): self
    {
        $this->anio = $anio;

        return $this;
    }

    public function getKilometraje(): ?int
    {
        return $this->kilometraje;
    }

    public function setKilometraje(int $kilometraje): self
    {
        $this->kilometraje = $kilometraje;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getPlazas(): ?int
    {
        return $this->plazas;
    }

    public function setPlazas(int $plazas): self
    {
        $this->plazas = $plazas;

        return $this;
    }

    public function getPuertas(): ?int
    {
        return $this->puertas;
    }

    public function setPuertas(?int $puertas): self
    {
        $this->puertas = $puertas;

        return $this;
    }

    public function getCambio(): ?Cambio
    {
        return $this->cambio;
    }

    public function setCambio(?Cambio $cambio): self
    {
        $this->cambio = $cambio;

        return $this;
    }

    public function getCombustible(): ?Combustible
    {
        return $this->combustible;
    }

    public function setCombustible(?Combustible $combustible): self
    {
        $this->combustible = $combustible;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getFechaAlta(): ?\DateTimeInterface
    {
        return $this->fecha_alta;
    }

    public function setFechaAlta(?\DateTimeInterface $fecha_alta): self
    {
        $this->fecha_alta = $fecha_alta;

        return $this;
    }

    public function getFechaReserva(): ?\DateTimeInterface
    {
        return $this->fecha_reserva;
    }

    public function setFechaReserva(?\DateTimeInterface $fecha_reserva): self
    {
        $this->fecha_reserva = $fecha_reserva;

        return $this;
    }

    public function getFechaVenta(): ?\DateTimeInterface
    {
        return $this->fecha_venta;
    }

    public function setFechaVenta(?\DateTimeInterface $fecha_venta): self
    {
        $this->fecha_venta = $fecha_venta;

        return $this;
    }

    public function getFechaModificacion(): ?\DateTimeInterface
    {
        return $this->fecha_modificacion;
    }

    public function setFechaModificacion(?\DateTimeInterface $fecha_modificacion): self
    {
        $this->fecha_modificacion = $fecha_modificacion;

        return $this;
    }

    public function getCondicion(): ?Condicion
    {
        return $this->condicion;
    }

    public function setCondicion(?Condicion $condicion): self
    {
        $this->condicion = $condicion;

        return $this;
    }

    public function getEstado(): ?Estado
    {
        return $this->estado;
    }

    public function setEstado(?Estado $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getImagenDestacada(): ?Media
    {
        return $this->imagen_destacada;
    }

    public function setImagenDestacada(Media $imagen_destacada): self
    {
        $this->imagen_destacada = $imagen_destacada;

        return $this;
    }

    public function getVideo(): ?Media
    {
        return $this->video;
    }

    public function setVideo(?Media $video): self
    {
        $this->video = $video;

        return $this;
    }
//
//    public function getGaleria(): ?Gallery
//    {
//        return $this->galeria;
//    }
//
//    public function setGaleria(?Gallery $galeria): self
//    {
//        $this->galeria = $galeria;
//
//        return $this;
//    }

    /**
     * @return Collection|self[]
     */
    public function getAutomovil(): Collection
    {
        return $this->automovil;
    }

    public function addAutomovil(self $automovil): self
    {
        if (!$this->automovil->contains($automovil)) {
            $this->automovil[] = $automovil;
        }

        return $this;
    }

    public function removeAutomovil(self $automovil): self
    {
        if ($this->automovil->contains($automovil)) {
            $this->automovil->removeElement($automovil);
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getRelacionados(): Collection
    {
        return $this->relacionados;
    }

    public function addRelacionado(self $relacionado): self
    {
        if (!$this->relacionados->contains($relacionado)) {
            $this->relacionados[] = $relacionado;
            $relacionado->addAutomovil($this);
        }

        return $this;
    }

    public function removeRelacionado(self $relacionado): self
    {
        if ($this->relacionados->contains($relacionado)) {
            $this->relacionados->removeElement($relacionado);
            $relacionado->removeAutomovil($this);
        }

src/Entity/GoogleReview.php
<?php

namespace App\Entity;

use App\Application\Sonata\MediaBundle\Entity\Media;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GoogleReviewRepository")
 */
class GoogleReview
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $opinion;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\Column(type="integer")
     */
    private $opiniones;

    /**
     * @ORM\OneToOne(targetEntity="App\Application\Sonata\MediaBundle\Entity\Media", cascade={"persist", "remove"})
     */
    private $imagen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_completo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOpinion(): ?string
    {
        return $this->opinion;
    }

    public function setOpinion(string $opinion): self
    {
        $this->opinion = $opinion;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getOpiniones(): ?int
    {
        return $this->opiniones;
    }

    public function setOpiniones(int $opiniones): self
    {
        $this->opiniones = $opiniones;

        return $this;
    }

    public function getImagen(): ?Media
    {
        return $this->imagen;
    }

    public function setImagen(?Media $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getNombreCompleto(): ?string
    {
        return $this->nombre_completo;
    }

    public function setNombreCompleto(string $nombre_completo): self
    {
        $this->nombre_completo = $nombre_completo;

        return $this;
    }
}

src/Controller/LayoutController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Automovil;
use App\Entity\GoogleReview;
use App\Entity\Legal;
use App\Entity\Cookie;
use App\Entity\PoliticaPrivacidad;
use App\Entity\Contacto;

class LayoutController extends AbstractController
{
    /**
     * @Route("/ultimos", name="ultimos")
     */
    public function getUltimosModelos(EntityManagerInterface $entityManager)
    {
    	$ultimos = $entityManager->getRepository(Automovil::class)->findBy([], ['id' => 'DESC'], 3);
        return $this->render('layout/ultimos.html.twig', [
            'controller_name' => 'LayoutController',
            'ultimos' => $ultimos,
        ]);
    }

    /**
     * @Route("/comentarios", name="comentarios")
     */
    public function getComentarios(EntityManagerInterface $entityManager, $max)
    {

        $comentarios = $entityManager->getRepository(GoogleReview::class)->findBy([], ['id' => 'DESC'], 5);
        return $this->render('layout/comentarios.html.twig', [
            'controller_name' => 'LayoutController',
            'comentarios' => $comentarios,
        ]);
    }

    /**
     * @Route("/politica-cookies", name="cookies")
    */
    public function cookies(EntityManagerInterface $entityManager) {
        $contacto = $entityManager->getRepository(Contacto::class)->findOneBy(['id' => 1]);
        $cookies = $entityManager->getRepository(Cookie::class)->findOneBy(['id' => 1]);
        return $this->render('partials/politicas.html.twig', [
            'controller_name' => 'LayoutController',
            'content' => $cookies,
            'flag' => 'politica_cookies',
            'contacto' => $contacto,
        ]);
    }

    /**
     * @Route("/aviso-legal", name="legal")
    */
    public function legal(EntityManagerInterface $entityManager) {
        $contacto = $entityManager->getRepository(Contacto::class)->findOneBy(['id' => 1]);
        $legal = $entityManager->getRepository(Legal::class)->findOneBy(['id' => 1]);
        return $this->render('partials/politicas.html.twig', [
            'controller_name' => 'LayoutController',
            'content' => $legal,
            'flag' => 'aviso_legal',
            'contacto' => $contacto,
        ]);
    }

    /**
     * @Route("/politica-privacidad", name="privacidad")
    */
    public function privacidad(EntityManagerInterface $entityManager) {
        $contacto = $entityManager->getRepository(Contacto::class)->findOneBy(['id' => 1]);
        $privacidad = $entityManager->getRepository(PoliticaPrivacidad::class)->findOneBy(['id' => 1]);
        return $this->render('partials/politicas.html.twig', [
            'controller_name' => 'LayoutController',
            'content' => $privacidad,
            'flag' => 'politica_privacidad',
            'contacto' => $contacto,
        ]);
    }
}

templates/layout/automovil.html.twig
<a href="{{ path('automovil', {'marca': automovil.marca|lower|replace({' ':''}), 'modelo': automovil.modelo|lower|replace({' ':'', '-':'_'}), 'id': automovil.id }) }}" class="car-img">
   <div class="car-box">
    <div class="car-thumbnail">
        {% if automovil.destacado %}
            <div class="tag">Destacado</div>
        {% endif %}
        <div class="price-box">€{{ automovil.precio }}</div>
        
        {% if automovil.imagenDestacada %}
            <img class="d-block w-100" src="{% path automovil.imagenDestacada, 'reference' %}" alt="car">
        {% else %}
            <img class="d-block w-100" src="http://placehold.it/350x233" alt="car">
        {% endif %}
        
    </div>
    <div class="detail">
        <h1 class="title">
            <a href="{{ path('automovil', {'marca': automovil.marca|lower|replace({' ':''}), 'modelo': automovil.modelo|lower|replace({' ':'', '-':'_'}), 'id': automovil.id }) }}">{{ automovil.marca }} {{automovil.modelo}}</a>
        </h1>
        <div class="location">
            <a href="{{ path('automovil', {'marca': automovil.marca|lower|replace({' ':''}), 'modelo': automovil.modelo|lower|replace({' ':'', '-':'_'}), 'id': automovil.id }) }}">
                <i class="flaticon-pin"></i>Ctra. de Agost, 128, 03690 San Vicente del Raspeig, Alicante
            </a>
        </div>
        <ul class="facilities-list clearfix">
            <li>
                <i class="flaticon-way"></i> {{ automovil.kilometraje }} km
            </li>
            <li>
                <i class="flaticon-manual-transmission"></i> {{ automovil.cambio }}
            </li>
            <li>
                <i class="flaticon-calendar-1"></i> {{ automovil.anio }}
            </li>
            <li>
                <i class="flaticon-fuel"></i> {{ automovil.combustible }}
            </li>
            <li>
                <i class="flaticon-car"></i> {{ automovil.color }}
            </li>
            {% if automovil.potencia %}
                <li>
                    <i class="flaticon-gear"></i> {{ automovil.potencia }}
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</a>

templates/layout/comentarios.html.twig
<div class="slick-slider-area">
    <div class="row slick-carousel" data-slick='{"slidesToShow": 2, "responsive":[{"breakpoint": 1024,"settings":{"slidesToShow": 2}}, {"breakpoint": 768,"settings":{"slidesToShow": 1}}]}'>
        {% for comentario in comentarios %}
            <div class="slick-slide-item">
                <div class="testimonial-inner">
                    <div class="text-box">
                        <p>{{ comentario.opinion }}</p>
                        <div class="rating">
                            {% for i in 1..comentario.rating %}
                                <i class="fa fa-star"></i>
                            {% endfor %}
                            {% if comentario.rating < 5 %}
                                {% for i in 1..(5 - comentario.rating) %}
                                    <i class="fa fa-star-o"></i>
                                {% endfor %}
                            {% endif %}
                            <span>( {{ comentario.opiniones }} Reviews )</span>
                        </div>
                    </div>
                    <div class="user">
                        <div class="photo">
                            {% if comentario.imagen %}
                                <img class="media-object" src="{% path comentario.imagen, 'reference' %}" alt="user">
                            {% else %}
                                <img class="media-object" src="http://placehold.it/50x50" alt="user">
                            {% endif %}
                        </div>
                        <div class="detail">
                            <h5>{{ comentario.nombreCompleto }}</h5>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="slick-prev slick-arrow-buton">
        <i class="fa fa-angle-left"></i>
    </div>
    <div class="slick-next slick-arrow-buton">
        <i class="fa fa-angle-right"></i>
    </div>
</div>

templates/layout/post.html.twig
<div class="blog-1">
    <div class="blog-photo">
       {% if post.image %}
        <img class="media-object" src="{% path post.image, 'reference' %}" alt="small-blog" class="img-fluid">
    {% else %}
        <img src="http://placehold.it/350x253" alt="small-blog" class="img-fluid">
    {% endif %}
    <div class="date-box">
        <span>{{ post.publicationDateStart|date('d') }}</span>{{ post.publicationDateStart|date('M') }}
    </div>
</div>
<div class="detail">
    <h4>
        <a href="{{ path('post', {'title': post.title|lower|replace({' ':''}), 'id': post.id  } ) }}">{{ post.title }}</a>
    </h4>
    <div class="post-meta clearfix">
        <span><a href="#"><i class="flaticon-user-1"></i></a>{{ post.author }}</span>
        <span><a href="#"><i class="flaticon-comment"></i></a>{{ post.commentsCount }}</span>
    </div>
    <p>{{ post.abstract|raw }}</p>
</div>
</div>

templates/layout/sidebarSearch.html.twig
<div class="widget search-box">
    <h3 class="sidebar-title">BUSCAR</h3>
    <div class="s-border"></div>
    <form class="form-inline form-search" method="POST">
        <div class="form-group">
            <label class="sr-only" for="textsearch2">Busca Novedades y Ofertas</label>
            <input type="text" class="form-control" id="textsearch2" name="search" placeholder="Busca Novedades y Ofertas">
        </div>
        <button type="submit" class="btn"><i class="fa fa-search"></i></button>
    </form>
</div>  

templates/layout/ultimos.html.twig
{% for ultimo in ultimos %}
    <div class="media mb-4">
        <a class="pr-3" href="{{ path('automovil', {'marca': ultimo.marca|lower|replace({' ':''}), 'modelo': ultimo.modelo|lower|replace({' ':'', '-':'_'}), 'id': ultimo.id }) }}">
            {% media ultimo.imagenDestacada, 'small' with {'class': 'media-object'} %}
        </a>
        <div class="media-body align-self-center">
            <h5>
                <a href="{{ path('automovil', {'marca': ultimo.marca|lower|replace({' ':''}), 'modelo': ultimo.modelo|lower|replace({' ':'', '-':'_'}), 'id': ultimo.id }) }}">{{ ultimo.marca }} {{ ultimo.modelo }}</a>
            </h5>
            <div class="listing-post-meta">
                €{{ ultimo.precio }} {% if ultimo.fechaAlta %}| <a href="{{ path('automovil', {'marca': ultimo.marca|lower|replace({' ':''}), 'modelo': ultimo.modelo|lower|replace({' ':'', '-':'_'}), 'id': ultimo.id }) }}"><i class="fa fa-calendar"></i>{{ ultimo.fechaAlta|date('M') }} {{ ultimo.fechaAlta|date('d') }}, {{ ultimo.fechaAlta|date('Y') }}</a>{% endif %}
            </div>
        </div>
    </div>
{% endfor %}